name: craft
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - --index-url https://pypi.tuna.tsinghua.edu.cn/simple
      - -e .[dev]
