"""Security protocol operations for CRAFT."""

from craft.security.approval import (
    build_approval_set,
    create_approval,
    explain_approval,
    explain_approval_set,
    verify_approval,
    verify_approval_set,
)
from craft.security.audit import (
    AuditChain,
    ProtocolTranscript,
    build_protocol_transcript,
    explain_audit_chain,
    explain_audit_event,
    export_protocol_transcript_json,
    issue_audit_event,
)
from craft.security.crypto import (
    PrincipalRegistry,
    RoleCredential,
    SM2KeyPair,
    TrustedPrincipal,
    create_demo_credentials,
    create_dispatcher_credential,
    create_evaluator_credential,
    create_gateway_credential,
    create_operator_credential,
    create_role_credential,
    create_safety_officer_credential,
    derive_sm2_public_key,
    generate_sm2_keypair,
    public_key_digest,
    sign_digest_hex,
    sign_payload,
    verify_digest_hex,
    verify_payload,
)
from craft.security.errors import ProtocolErrorCode, VerificationResult
from craft.security.pcc import (
    explain_pcc,
    explain_pcc_for_action,
    issue_pcc,
    verify_pcc,
    verify_pcc_for_action,
)
from craft.security.policy import (
    DEFAULT_RISK_POLICY,
    RiskPolicy,
    RiskPolicyRule,
    ensure_risk_is_authorizable,
    ensure_role_can_approve,
    required_roles_for_risk,
)
from craft.security.protocol import (
    AuthorizedAction,
    CertifiedAction,
    ExecutedAction,
    SecurityProtocol,
    TicketedAction,
    create_demo_security_protocol,
)
from craft.security.receipt import (
    explain_execution_receipt,
    issue_execution_receipt,
    verify_execution_receipt,
)
from craft.security.ticket import (
    TicketReplayCache,
    consume_execution_ticket,
    explain_consume_execution_ticket,
    explain_execution_ticket,
    issue_execution_ticket,
    verify_execution_ticket,
)

__all__ = [
    "DEFAULT_RISK_POLICY",
    "AuditChain",
    "AuthorizedAction",
    "CertifiedAction",
    "ExecutedAction",
    "PrincipalRegistry",
    "ProtocolTranscript",
    "ProtocolErrorCode",
    "RiskPolicy",
    "RiskPolicyRule",
    "RoleCredential",
    "SM2KeyPair",
    "SecurityProtocol",
    "TicketReplayCache",
    "TicketedAction",
    "TrustedPrincipal",
    "VerificationResult",
    "build_approval_set",
    "build_protocol_transcript",
    "consume_execution_ticket",
    "create_approval",
    "create_demo_credentials",
    "create_demo_security_protocol",
    "create_dispatcher_credential",
    "create_evaluator_credential",
    "create_gateway_credential",
    "create_operator_credential",
    "create_role_credential",
    "create_safety_officer_credential",
    "derive_sm2_public_key",
    "ensure_risk_is_authorizable",
    "ensure_role_can_approve",
    "explain_approval",
    "explain_approval_set",
    "explain_audit_chain",
    "explain_audit_event",
    "explain_consume_execution_ticket",
    "explain_execution_receipt",
    "explain_execution_ticket",
    "explain_pcc",
    "explain_pcc_for_action",
    "generate_sm2_keypair",
    "export_protocol_transcript_json",
    "issue_audit_event",
    "issue_execution_receipt",
    "issue_execution_ticket",
    "issue_pcc",
    "public_key_digest",
    "required_roles_for_risk",
    "sign_digest_hex",
    "sign_payload",
    "verify_approval",
    "verify_approval_set",
    "verify_digest_hex",
    "verify_execution_receipt",
    "verify_execution_ticket",
    "verify_payload",
    "verify_pcc",
    "verify_pcc_for_action",
]
